version: '2'
services:
  nginx:
    container_name: nginx-image_resize-container
    build:
      context: ./nginx
    ports:
        - 8888:80
    volumes:
      - ./nginx/images:/etc/nginx/html/images/
